server:
  port: ${SERVER_PORT:8082}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cognitron}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cognitron:
  rabbitmq:
    queue: ${RABBITMQ_QUEUE:content-crawl-queue}
    exchange: ${RABBITMQ_EXCHANGE:cognitron.exchange}
    routing-key: ${RABBITMQ_ROUTING_KEY:crawl.task}
    discovered-routing-key: ${RABBITMQ_DISCOVERED_ROUTING_KEY:crawl.discovered}
    discovered-queue: ${RABBITMQ_DISCOVERED_QUEUE:discovered-links-queue}

  crawl:
    global-max-pages-per-24h: ${GLOBAL_MAX_PAGES_PER_24H:200}

rabbitmq:
  management:
    url: ${RABBITMQ_MANAGEMENT_URL:http://localhost:15672}
    username: ${RABBITMQ_MANAGEMENT_USER:guest}
    password: ${RABBITMQ_MANAGEMENT_PASS:guest}