spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cognitron}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: ${SERVER_PORT:8082}