server:
  port: ${SERVER_PORT:8081}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jackson:
    serializer:
      indent_output: true

cognitron:
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:cognitron.exchange}
    routing-key: ${RABBITMQ_ROUTING_KEY:crawl.task}
    discovered-routing-key: ${RABBITMQ_DISCOVERED_ROUTING_KEY:crawl.discovered}
    queue: ${RABBITMQ_QUEUE:content-crawl-queue}
    discovered-queue: ${RABBITMQ_DISCOVERED_QUEUE:discovered-links-queue}