server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jackson:
    serializer:
      indent_output: true

cognitron:
  rabbitmq:
    exchange: cognitron.exchange
    routing-key: crawl.task
    discovered-routing-key: crawl.discovered
    queue: content-crawl-queue
    discovered-queue: discovered-links-queue
